version: '3.9'
services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    ports:
      - '5050:80'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  db-volume:
  pgadmin-volume:

networks:
  postgres:
    driver: bridge
