/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clevertec;


import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
    }
}
